# Generated by Django 4.2.2 on 2024-01-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockserialhistory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.store'),
        ),
    ]
