# Generated by Django 4.2.2 on 2024-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='HistoryDetails',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
