# Generated by Django 4.2.2 on 2024-03-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_groups_name',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.item_groups_name'),
        ),
    ]
