# Generated by Django 4.2.2 on 2024-03-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_item_groups_name_parent_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsgroup',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='accountsgroup',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='accountsgroup',
            old_name='isDelete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='accountsgroup',
            old_name='UpdatedAt',
            new_name='updated_at',
        ),
    ]
