# Generated by Django 4.2.2 on 2024-02-13 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_alter_salesorder_marketingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchnumber',
            name='part_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AlterField(
            model_name='inventoryhandler',
            name='Store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AlterField(
            model_name='item_combo',
            name='part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AlterField(
            model_name='iteminventoryapproval',
            name='Store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AlterField(
            model_name='iteminventoryapproval',
            name='part_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='part_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='partCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AlterField(
            model_name='stockhistorylog',
            name='PartNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AlterField(
            model_name='stockhistorylog',
            name='StoreLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AlterField(
            model_name='stockserialhistory',
            name='part_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AlterField(
            model_name='stockserialhistory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
    ]
