# Generated by Django 4.2.2 on 2024-01-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_alter_stockserialhistory_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorylog',
            name='PartNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.itemmaster'),
        ),
    ]
