# Generated by Django 4.2.2 on 2024-02-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_alter_contact_detalis_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststaantable',
            name='Salary',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='BillingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillingAddress', to='itemmaster.company_address'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='DeliverAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DeliverAddress', to='itemmaster.company_address'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='WhatsappNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
