# Generated by Django 4.2.2 on 2024-02-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_itemmaster_historydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='HistoryDetails',
        ),
        migrations.DeleteModel(
            name='ItemMasterHistory',
        ),
    ]
