# Generated by Django 4.2.2 on 2024-02-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0003_alter_batchnumber_part_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate_unit',
            name='addtional_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AlterField(
            model_name='iteminventoryapproval',
            name='UOM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Item_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group', to='itemmaster.item_groups_name'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Item_UOM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='itemmaster.uom'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Purchase_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uom', to='itemmaster.uom'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='UOM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
    ]
