# Generated by Django 4.2.2 on 2024-01-29 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0003_stockhistorylog_partnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistorylog',
            name='StoreLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.store'),
        ),
    ]
