# Generated by Django 4.2.2 on 2024-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_salesorder_pos_id_itemmasterhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmaster',
            name='AccountType',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Tax', 'Tax'), ('Cash', 'Cash')], max_length=20, null=True),
        ),
    ]
