# Generated by Django 4.2.2 on 2024-01-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_stockhistorylog_storelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='supplierData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.supplier_form_data'),
        ),
    ]
