# Generated by Django 4.2.2 on 2024-03-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_rename_createdat_accountsmaster_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternate_unit',
            old_name='CreatedAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='alternate_unit',
            old_name='createdby',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='alternate_unit',
            old_name='isDelete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='alternate_unit',
            old_name='UpdatedAt',
            new_name='updated_at',
        ),
    ]
