# Generated by Django 4.2.2 on 2024-02-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_alter_alternate_unit_addtional_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmaster',
            name='Accounts_Group_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsgroup'),
        ),
        migrations.AlterField(
            model_name='item_groups_name',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Item_HSN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Item_Purchase_Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Accounts_Master_Purchase_Account', to='itemmaster.accountsmaster'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='Item_Sales_Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Accounts_Master_Sales_Account', to='itemmaster.accountsmaster'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencymaster'),
        ),
        migrations.AlterField(
            model_name='store',
            name='StoreAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster'),
        ),
    ]
