# Generated by Django 4.2.2 on 2024-02-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_itemmasterhistory_itemmaster_historydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmasterhistory',
            name='ColumnName',
        ),
        migrations.RemoveField(
            model_name='itemmasterhistory',
            name='PreviousState',
        ),
    ]
