# Generated by Django 4.2.2 on 2024-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0005_itemmaster_supplierdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
