# Generated by Django 4.2.2 on 2024-03-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0005_rename_createdat_alternate_unit_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternate_unit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alternate_unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='alternate_unit',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='alternate_unit',
            name='updated_at',
        ),
    ]
