# Generated by Django 4.2.2 on 2024-01-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0006_alter_salesorderitem_cgst_alter_salesorderitem_igst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='BillingAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillingAddress', to='itemmaster.company_address'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='DeliverAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DeliverAddress', to='itemmaster.company_address'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.supplier_form_data'),
        ),
    ]
