# Generated by Django 4.2.2 on 2024-02-20 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0006_itemmasterhistory_columnname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createItemmaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
