# Generated by Django 4.2.2 on 2024-01-31 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0007_salesorder_billingaddress_salesorder_deliveraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='Batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.batchnumber'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='Serial',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
    ]
