# Generated by Django 4.2.2 on 2024-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0007_itemmaster_createdat_itemmaster_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmasterhistory',
            name='UpdatedState',
            field=models.TextField(max_length=250),
        ),
    ]
