# Generated by Django 4.2.2 on 2024-02-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0008_salesorderitem_batch_salesorderitem_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='store',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.store'),
        ),
    ]
