# Generated by Django 4.2.2 on 2024-02-21 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0008_alter_itemmasterhistory_updatedstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='isclosed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='paymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BalanceAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Payby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.paymentmode'),
        ),
    ]
