# Generated by Django 4.2.2 on 2024-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0009_remove_salesorderitem_store_salesorder_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
