# Generated by Django 4.2.2 on 2024-02-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0009_salesorder_isclosed_alter_salesorder_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmasterhistory',
            name='UpdatedState',
            field=models.TextField(max_length=2500),
        ),
    ]
