# Generated by Django 4.2.2 on 2024-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0010_alter_salesorder_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='WhatsappNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
