# Generated by Django 4.2.2 on 2024-02-21 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0010_alter_itemmasterhistory_updatedstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='isclosed',
            new_name='isDelivered',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='SalesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
