# Generated by Django 4.2.2 on 2024-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0011_salesorder_whatsappnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='City',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
