# Generated by Django 4.2.2 on 2024-02-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0011_rename_isclosed_salesorder_isdelivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_form_data',
            name='Saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Saved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplier_form_data',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesPerson', to=settings.AUTH_USER_MODEL),
        ),
    ]
