# Generated by Django 4.2.2 on 2024-02-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0012_alter_supplier_form_data_saved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='Status',
            field=models.CharField(blank=True, choices=[('Save', 'Save'), ('Submit', 'Submit'), ('Cancel', 'Cancel')], max_length=10, null=True),
        ),
    ]
