# Generated by Django 4.2.2 on 2024-02-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0013_salesorderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='Pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Save', 'Save'), ('Submit', 'Submit'), ('Cancel', 'Cancel')], max_length=50, null=True),
        ),
    ]
