# Generated by Django 4.2.2 on 2024-02-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0014_salesorder_pending_salesorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmode',
            old_name='BalanceAmount',
            new_name='balance_amount',
        ),
        migrations.RenameField(
            model_name='paymentmode',
            old_name='payAmount',
            new_name='pay_amount',
        ),
        migrations.RenameField(
            model_name='paymentmode',
            old_name='Payby',
            new_name='payby',
        ),
    ]
