# Generated by Django 4.2.2 on 2024-02-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0015_rename_balanceamount_paymentmode_balance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='Currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencymaster'),
        ),
    ]
