# Generated by Django 4.2.2 on 2024-02-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0017_alter_salesorder_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='payment',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment',
            field=models.ManyToManyField(null=True, to='itemmaster.paymentmode'),
        ),
    ]
