# Generated by Django 4.2.2 on 2024-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0020_store_createdat_store_updatedat_store_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='HistoryDetails',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
