# Generated by Django 4.2.2 on 2024-02-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0022_alter_salesorder_billingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('isDelete', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routingScreate', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routingmodified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BomName', models.CharField(max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('Action', models.BooleanField(default=True)),
                ('Default', models.BooleanField(default=True)),
                ('LabourCharges', models.JSONField(blank=True, null=True)),
                ('MachineryCharges', models.JSONField(blank=True, null=True)),
                ('ElectricityCharges', models.JSONField(blank=True, null=True)),
                ('OtherCharges', models.JSONField(blank=True, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('FgStore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FgStore', to='itemmaster.store')),
                ('RoutingLink', models.ManyToManyField(blank=True, to='itemmaster.routing')),
                ('ScrapRejectStore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ScrapRejectStore', to='itemmaster.store')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bom_create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bom_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
