# Generated by Django 4.2.2 on 2024-02-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0025_alter_finishedgoods_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoods',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='Category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
