# Generated by Django 4.2.2 on 2024-02-24 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0026_finishedgoods_category_rawmaterial_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='FinishedGoodsLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.finishedgoods'),
        ),
        migrations.AddField(
            model_name='bom',
            name='RawMaterialLink',
            field=models.ManyToManyField(blank=True, to='itemmaster.rawmaterial'),
        ),
        migrations.AddField(
            model_name='bom',
            name='ScrapLink',
            field=models.ManyToManyField(blank=True, to='itemmaster.scrap'),
        ),
    ]
