# Generated by Django 4.2.2 on 2024-02-24 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0027_bom_finishedgoodslink_bom_rawmateriallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_groups_name',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_groups_name',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item_groups_name',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IGcreate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item_groups_name',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item_groups_name',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IGmodified', to=settings.AUTH_USER_MODEL),
        ),
    ]
