# Generated by Django 4.2.2 on 2024-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0028_item_groups_name_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_groups_name',
            name='HistoryDetails',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
