# Generated by Django 4.2.2 on 2024-02-26 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0031_accountsgroup_createdat_accountsgroup_historydetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsn',
            name='created_at',
        ),
        migrations.AddField(
            model_name='hsn',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hsn',
            name='HistoryDetails',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='hsn',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hsn',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_Hsn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hsn',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hsn',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_Hsn', to=settings.AUTH_USER_MODEL),
        ),
    ]
