# Generated by Django 4.2.2 on 2024-02-26 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0032_remove_hsn_created_at_hsn_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyexchange',
            name='SavedBy',
        ),
        migrations.RemoveField(
            model_name='currencymaster',
            name='SavedBy',
        ),
        migrations.RemoveField(
            model_name='currencymaster',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='HistoryDetails',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_CurrencyExchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_CurrencyExchange', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='HistoryDetails',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='UpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_CurrencyMaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_CurrencyMaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencymaster',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
