# Generated by Django 4.2.2 on 2024-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0034_routing_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchnumber',
            name='BatchNumberName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
