# Generated by Django 4.2.2 on 2024-02-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0037_salesorder_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='payment',
            field=models.ManyToManyField(blank=True, to='itemmaster.paymentmode'),
        ),
    ]
