# Generated by Django 4.2.2 on 2024-02-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0039_alter_salesorderitem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='contactPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.contact_detalis'),
        ),
    ]
