# Generated by Django 4.2.2 on 2024-03-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0040_salesorder_contactperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='receivedAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
