# Generated by Django 4.2.2 on 2023-11-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencedata',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='conferencedata',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='conferencedata',
            name='incharge',
        ),
        migrations.RemoveField(
            model_name='conferencedata',
            name='startDate',
        ),
    ]
