# Generated by Django 4.2.2 on 2024-02-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_salesorder_pos_id_itemmasterhistory'),
        ('EnquriFromapi', '0002_conferencedata_defaultstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencedata',
            name='Currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.currencymaster'),
        ),
        migrations.AlterField(
            model_name='conferencedata',
            name='DefaultStore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.store'),
        ),
    ]
