# Generated by Django 4.2.2 on 2023-11-10 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnquriFromapi', '0002_remove_conferencedata_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencedata',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferencedata',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conferencedata',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferencedata',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
