# Generated by Django 4.2.2 on 2023-11-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0005_conferencedata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencedata',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
