# Generated by Django 4.2.2 on 2023-11-28 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0006_alter_conferencedata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydatas',
            name='Interesteds',
            field=models.ManyToManyField(blank=True, null=True, to='EnquriFromapi.product'),
        ),
        migrations.AlterField(
            model_name='enquirydatas',
            name='MobileNumber',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?9?1?\\s?-?\\d{5}\\s?\\d{5}$')]),
        ),
    ]
