# Generated by Django 4.2.2 on 2023-11-29 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EnquriFromapi', '0007_alter_enquirydatas_interesteds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydatas',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='followup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='salesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
