# Generated by Django 4.2.2 on 2023-11-30 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0008_enquirydatas_remarks_enquirydatas_followup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydatas',
            name='alternateMobileNumber',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?9?1?\\s?-?\\d{5}\\s?\\d{5}$')]),
        ),
    ]
