# Generated by Django 4.2.2 on 2023-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0009_enquirydatas_alternatemobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydatas',
            name='Interesteds',
            field=models.ManyToManyField(blank=True, to='EnquriFromapi.product'),
        ),
    ]
