# Generated by Django 4.2.2 on 2023-12-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0011_alter_enquirydatas_mobilenumber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
