# Generated by Django 4.2.2 on 2024-01-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0012_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydatas',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
        migrations.AlterField(
            model_name='enquirydatas',
            name='status',
            field=models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Converted', 'Converted'), ('Junk', 'Junk'), ('Inprogress', 'Inprogress')], max_length=50),
        ),
    ]
