# Generated by Django 4.2.2 on 2024-01-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0013_enquirydatas_profile_image_alter_enquirydatas_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydatas',
            name='Remarks',
        ),
    ]
