# Generated by Django 4.2.2 on 2024-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0014_remove_enquirydatas_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydatas',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
